#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
# if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
#   source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
# fi

# Customize to your needs...


export BASH_PROFILE="${HOME}/.bash_profile"

# shellcheck source=.bash_profile
[[ -s ${BASH_PROFILE} ]] && source "${BASH_PROFILE}"
